### ISSUE TITLE
could you provide info on the tables in some human readable form?

### ISSUE THREAD

**Issue by rgentlem** [ccb-hms/GWASCatalogSearchDB#1]
When trying to write an R version of the interface into the DB (and just generally describing it), it would be really helpful to have some sort of schema information for gwascatalog_search.db,  what tables, and for the tables what columns....

**Comment by rsgoncalves** [comment]
Agreed. The README now provides an image with the tables and their columns, and a more detailed description of some table columns below the image. Would this be enough detail?

**Comment by rsgoncalves** [comment]
Closed via 57c7170
