### ISSUE TITLE
version info on the readme page

### ISSUE THREAD

**Issue by rgentlem** [ccb-hms/GWASCatalogSearchDB#11]
Hi 
  Just wondering if it would be possible to put this information on the readme - and have it updated for each release
> RSQLite::dbGetQuery(gwasCatSearch_dbconn(), "SELECT * from version_info")
      Resource             Version
1      Studies 2023-08-29T09:46:50
2 Associations 2023-08-29T09:48:19
3          EFO              3.43.0

that just makes it much easier to check that I am working with the current version....

**Comment by rsgoncalves** [comment]
Hi Robert. Yes absolutely. I will also include our sqlite DB release version in that version_info table (both in the Readme and in the DB), to be more complete.
