### ISSUE TITLE
issue with the

### ISSUE THREAD

**Issue by rgentlem** [ccb-hms/GWASCatalogSearchDB#16]
Can you confirm that this query 
"SELECT * from efo_entailed_edges where Object IN ('MONDO:0019640','EFO:0004194')"
is supposed to return the following:
       Subject        Object
1   EFO:0004194   EFO:0004194
2 MONDO:0019640 MONDO:0019640

This seems to imply that there are self-loops in the entailed_edges graph - which I can work around, but I am
not sure they should be there.
One reasonable definition for a leaf node is that it has no children - and then I would expect the entailed_edges table to
report that.  But it doesn't - I think this says if I ask about a node, I always get itself as an entailed_edge.

**Comment by rsgoncalves** [comment]
Yes, that is the expected result from the query since every class is entailed to be a subclass of itself (every set is a subset of itself). I think statements such as those are not present in the efo_edges table, which contains only asserted edges.

**Comment by rgentlem** [comment]
thanks - I will work with that
