### ISSUE TITLE
this seems odd

### ISSUE THREAD

**Issue by rgentlem** [ccb-hms/GWASCatalogSearchDB#4]
Hi,
 In the data I am getting form efo_labels, I am seeing:
> ss = efo_df$Inherited
> sort(ss, dec=T)[1:20]
 [1] 32726 27590 10127  4405  3534  3078  2668  2037  1905  1699  1432  1381  1318  1296  1112
[16]  1011   906   899   886   872
> table(efo_df$Direct>0)

FALSE  TRUE 
23203  4013 

 which says only 4013 of them have direct mappings - but I don't see how we get such very large values for the indirect mappings? Can you check?

**Comment by rgentlem** [comment]
oops for Direct mappings I see:
sort(efo_df$Direct, dec=T)[1:10]
 [1] 2538 2150  958  454  405  387  369  318  298  286
and they are:
efo_df[efo_df$Direct>500,1]
[1] "EFO:0004747" "EFO:0007874" "EFO:0007937"

also the text string for the matching traits:
nchar(efo_df["EFO:0004747","Matches"])
[1] 141118
is very very long - seems like something might be amiss
and the rest of that record:
efo_df["EFO:0004747",1:7]
                Subject              Object                                  IRI
EFO:0004747 EFO:0004747 protein measurement http://www.ebi.ac.uk/efo/EFO_0004747
            DiseaseLocation Direct Inherited       Synonyms
EFO:0004747                   2150     10127 protein levels
something seems a bit off

**Comment by rgentlem** [comment]
More digging suggest that indeed they labeled 2538 traits only with EFO:0007937
which is [blood protein measurement](https://www.ebi.ac.uk/efo/EFO_0007937)
 - and it looks like a handful of other EFO labels were used similarly....
 - probably for a few papers on serum proteomics...yuck

**Comment by rsgoncalves** [comment]
I have been looking into this and it looks to me like the mapping counts are correct.  They are counted right off of the original metadata table. 

It does seem like many GWAS Catalog records are mapped to fairly generic EFO terms. I'll try to do a comparison with mappings generated using text2term.

**Comment by rgentlem** [comment]
thanks
